INSERT INTO `tasks`(`id`, `creation_time`, `name`, `category_id`, `description`, `location_id`, `budget`, `deadline`, `customer_id`, `status`) VALUES("1","2019-03-09","enable impactful technologies", "2","Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.","","6587","2019-11-15", "12", "Новое"),("2","2019-07-03","exploit revolutionary portals", "3","Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.

Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.","","2904","2019-12-07", "11", "Новое"),("3","2019-06-27","matrix next-generation e-commerce", "2","Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.","","1170","2019-11-23", "1", "Новое"),("4","2019-01-01","benchmark plug-and-play infomediaries", "1","Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.","","838","2019-11-10", "13", "Новое"),("5","2019-09-07","integrate cross-platform e-business", "3","Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.","","7484","2019-12-15", "12", "Новое"),("6","2018-11-01","enable dot-com niches", "7","Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.","","5725","2019-11-24", "7", "Новое"),("7","2019-09-13","transform web-enabled relationships", "5","Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.","","4414","2019-11-19", "3", "Новое"),("8","2019-04-01","strategize frictionless solutions", "8","Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.","","3454","2019-11-14", "21", "Новое"),("9","2019-03-28","innovate seamless metrics", "4","Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.","","3101","2019-12-12", "15", "Новое"),("10","2019-05-01","integrate wireless infomediaries", "4","Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.","","6562","2019-12-19", "20", "Новое")